Application Start Up.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
Application Start Up.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
An error occurred using the connection to database '""' on server '"localhost"'.
Application Start Up.
Application Start Up.
Application Start Up.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
Application Start Up.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
Application Start Up.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
Application Start Up.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
Application Start Up.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
An error occurred using the connection to database '""' on server '"db"'.
Application Start Up.
HTTP "GET" "/" responded 404 in 66.8221 ms
HTTP "GET" "/item/test" responded 200 in 162.8155 ms
HTTP "GET" "/favicon.ico" responded 404 in 0.6090 ms
Request all Items where TodoId = 1 from Repository.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
An exception occurred while iterating over the results of a query for context type '"TodoApp.API.Data.AppDbContext"'."
""Microsoft.EntityFrameworkCore.Storage.RetryLimitExceededException: Maximum number of retries (10) exceeded while executing database operations with 'MySqlRetryingExecutionStrategy'. See inner exception for the most recent failure.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()"
Microsoft.EntityFrameworkCore.Storage.RetryLimitExceededException: Maximum number of retries (10) exceeded while executing database operations with 'MySqlRetryingExecutionStrategy'. See inner exception for the most recent failure.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
HTTP "GET" "/item/1" responded 500 in 70507.1366 ms
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Object -> IEnumerable`1
System.Object -> System.Collections.Generic.IEnumerable`1[[TodoApp.API.DTOs.Item.ItemResponseDto, TodoApp.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
 ---> Microsoft.EntityFrameworkCore.Storage.RetryLimitExceededException: Maximum number of retries (10) exceeded while executing database operations with 'MySqlRetryingExecutionStrategy'. See inner exception for the most recent failure.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   at TodoApp.API.Handlers.Queries.Items.GetTodoItemsByIdHandler.Handle(GetTodoItemsByIdRequest request, CancellationToken cancellationToken) in D:\PPS SE\Training Projects\TodoApp.MVVM\src\TodoApp.API\TodoApp.API\Handlers\Queries\Items\GetTodoItemsByIdHandler.cs:line 50
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at TodoApp.API.Controllers.ItemController.GetAllItem(Int32 id) in D:\PPS SE\Training Projects\TodoApp.MVVM\src\TodoApp.API\TodoApp.API\Controllers\ItemController.cs:line 33
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
An unhandled exception has occurred while executing the request.
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Object -> IEnumerable`1
System.Object -> System.Collections.Generic.IEnumerable`1[[TodoApp.API.DTOs.Item.ItemResponseDto, TodoApp.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
 ---> Microsoft.EntityFrameworkCore.Storage.RetryLimitExceededException: Maximum number of retries (10) exceeded while executing database operations with 'MySqlRetryingExecutionStrategy'. See inner exception for the most recent failure.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   at TodoApp.API.Handlers.Queries.Items.GetTodoItemsByIdHandler.Handle(GetTodoItemsByIdRequest request, CancellationToken cancellationToken) in D:\PPS SE\Training Projects\TodoApp.MVVM\src\TodoApp.API\TodoApp.API\Handlers\Queries\Items\GetTodoItemsByIdHandler.cs:line 50
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at TodoApp.API.Controllers.ItemController.GetAllItem(Int32 id) in D:\PPS SE\Training Projects\TodoApp.MVVM\src\TodoApp.API\TodoApp.API\Controllers\ItemController.cs:line 33
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Application Start Up.
HTTP "GET" "/" responded 404 in 22.1831 ms
HTTP "GET" "/item/test" responded 200 in 119.8523 ms
HTTP "GET" "/favicon.ico" responded 404 in 0.5001 ms
Application Start Up.
Application Start Up.
Application Start Up.
HTTP "GET" "/item/test" responded 200 in 266.8516 ms
HTTP "GET" "/favicon.ico" responded 404 in 1.8274 ms
Request all Items where TodoId = 1 from Repository.
An error occurred using the connection to database '"ppg_todo"' on server '"db"'.
Application Start Up.
HTTP "GET" "/item/test" responded 200 in 415.9331 ms
HTTP "GET" "/favicon.ico" responded 404 in 1.8395 ms
Application Start Up.
Application Start Up.
HTTP "GET" "/item/test" responded 200 in 373.3186 ms
HTTP "GET" "/favicon.ico" responded 404 in 1.1387 ms
Request all Items where TodoId = 1 from Repository.
HTTP "GET" "/item/1" responded 200 in 746.1835 ms
Request all Items where TodoId = 1 from Repository.
HTTP "GET" "/item/1" responded 200 in 68.4908 ms
Request All Todo Data From Repository.
HTTP "GET" "/todo" responded 200 in 56.6769 ms
Request All Todo Data From Repository.
HTTP "GET" "/todo" responded 200 in 17.6145 ms
Application Start Up.
Request All Todo Data From Repository.
HTTP "GET" "/todo" responded 200 in 787.2538 ms
HTTP "GET" "/favicon.ico" responded 404 in 0.9369 ms
Request All Todo Data From Repository.
HTTP "GET" "/todo" responded 200 in 126.1998 ms
New Todo Successfully Created Id:2
HTTP "POST" "/todo" responded 201 in 469.8354 ms
Request Todo Id:21 To Update Not Found.
HTTP "PUT" "/todo/21" responded 404 in 80.7603 ms
The Todo Request Id:23 To Delete Not Found.
HTTP "DELETE" "/todo/23" responded 404 in 45.0383 ms
